<main class="main">
    <div class="connect">
        <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>connect.png">
    </div>
    <h1 class="main-h1">Bedankt voor uw bestelling bij PortofoonWEB!</h1>
    <h2 class="main-h2">Goed om te weten</h2>
    <p class="main-p">
        Bent u tevreden over het bestelproces like dan onze Facebook pagina of laat een review achter,
        zo maakt u ook nog eens kans op een leuke cadeau bon ter waarde van € 100,- Wilt u graag op de
        hoogte blijven van het laatste nieuws en speciale aanbiedingen meld u zich dan aan op onze nieuwsbrief.
    </p>
    <h2 class="main-h2">Wat gaat er nu gebeuren?</h2>
    <p class="main-p">
        Per email heeft u een bevestiging ontvangen van uw bestelling met Ordernummer [ordernummer].
        Heeft u de bestelling op een werkdag voor 17:00 gedaan en betaald, dan gaan wij nu direct aan
        de slag om te zorgen dat u het morgen in huis heeft. Heeft u vragen over de bestelling neem dan
        contact met ons op 0512 – 745293 of stuur ons een email aan info@portofoonweb.nl.
    </p>
    <h2 class="main-h2">Wist u dat?</h2>
    <p class="main-p">
        PortofoonWEB heeft sinds kort een fenomenaal nieuwe techniek genaamd Smart Portofoons.
        Een portofoon systeem met ongekende mogelijkheden en onbeperkt bereik!
        Klik op deze link voor meer informatie.
    </p>
    <div class="social">
        <ul class="social-ul">
            <li class="social-li"><img src="<?php echo $block->getUrl("pub/media/myfolder/")?>smart.png"></li>
            <li class="social-li">
                <a target="_blank" href="https://www.facebook.com/">
                    <span class="facebook"></span>
                </a>
            </li>
            <li class="social-li">
                <a target="_blank" href="https://twitter.com/">
                    <span class="twitter"></span>
                </a>
            </li>
        </ul>
    </div>

    <div class="slider">
        <ul>
            <li>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>motorola.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>baofeng.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>icom.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>hytera.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>kenwood.png"/>
            </li>
            <li>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>hytera.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>kenwood.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>icom.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>motorola.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>baofeng.png"/>
            </li>
            <li>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>kenwood.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>icom.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>motorola.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>baofeng.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>hytera.png"/>
            </li>
            <li>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>icom.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>motorola.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>baofeng.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>hytera.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>kenwood.png"/>
            </li>
            <li>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>motorola.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>baofeng.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>hytera.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>kenwood.png"/>
                <img src="<?php echo $block->getUrl("pub/media/myfolder/")?>icom.png"/>
            </li>
        </ul>
    </div>
</main>

